name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - jupyter
  - seaborn
  - pandas=1.4.4
  - pip=22.1.2
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - pip:
      - wandb==0.13.9